export const FETCH_CLIENTS = 'fetch_clients';
export const SUBMIT_CLIENT = 'submit_client';
export const ADD_CLIENT = 'add_client';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const ADD_ORDER_START = 'ADD_ORDER_START';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL';
export const REMOVE_ORDER = 'REMOVE_ORDER';

export const FETCH_SAMPLES_START = 'FETCH_SAMPLES';
export const FETCH_SAMPLES_SUCCESS = 'FETCH_SAMPLES_SUCCESS';
export const FETCH_SAMPLES_FAIL = 'FETCH_SAMPLES_FAIL';
export const ADD_SAMPLE = 'ADD_SAMPLE';
export const REMOVE_SAMPLE = 'REMOVE_SAMPLE';
export const FETCH_SAMPLES = 'FETCH_SAMPLES';

export const ADD_FINISH_START = 'ADD_FINISH_START';
export const ADD_FINISH_SUCCESS = 'ADD_FINISH_SUCCESS';
export const ADD_FINISH_FAIL = 'ADD_FINISH_FAIL';
export const REMOVE_FINISH = 'REMOVE_FINISH';
export const REMOVE_FINISH_MATERIAL = 'REMOVE_FINISH_MATERIAL';
export const ADD_FINISH_MATERIAL = 'ADD_FINISH_MATERIAL';
export const FETCH_FINISHES_START = 'FETCH_FINISHES_START';
export const FETCH_FINISHES_SUCCESS = 'FETCH_FINISHES_SUCCESS';
export const FETCH_FINISHES_FAIL = 'FETCH_FINISHES_FAIL';

export const FETCH_SELECTIONS = 'FETCH_SELECTIONS';
export const FETCH_FINISH_TYPES = 'FETCH_FINISH_TYPES';
export const FETCH_STOCK_LEVELS = 'FETCH_STOCK_LEVELS';
export const FETCH_MATERIALS = 'FETCH_MATERIALS';

export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const ADD_PRODUCT_START = 'ADD_PRODUCT_START';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

